/*
 * TestRegularExpressionDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package de.phleisch.app.itsucks.gui.common;

/**
 *
 * @author  __USER__
 */
public class TestRegularExpressionDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 1267650677497411057L;

	/** Creates new form TestRegularExpressionDialog */
	public TestRegularExpressionDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		editRegularExpression2Panel1 = new de.phleisch.app.itsucks.gui.common.panel.EditRegularExpressionPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Regular Expression Tester");
		setLocationByPlatform(true);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				editRegularExpression2Panel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				editRegularExpression2Panel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 311,
				Short.MAX_VALUE));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private de.phleisch.app.itsucks.gui.common.panel.EditRegularExpressionPanel editRegularExpression2Panel1;
	// End of variables declaration//GEN-END:variables

}