/*
 * EditDownloadJobFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package de.phleisch.app.itsucks.gui.job;

import java.awt.Dialog;
import java.awt.Frame;
import java.io.File;

import javax.swing.JOptionPane;

import de.phleisch.app.itsucks.gui.job.ifc.AddDownloadJobCapable;
import de.phleisch.app.itsucks.job.download.DownloadJob;
import de.phleisch.app.itsucks.persistence.SerializableJobPackage;

/**
 *
 * @author  __USER__
 */
public class EditDownloadJobDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 3587076557680397119L;

	private AddDownloadJobCapable mDownloadJobManager = null;

	/** Creates new form EditDownloadJobFrame */
	public EditDownloadJobDialog(Frame pOwner,
			AddDownloadJobCapable pDownloadJobManager) {

		super(pOwner);
		init(pDownloadJobManager);
	}

	public EditDownloadJobDialog(Dialog pOwner,
			AddDownloadJobCapable pDownloadJobManager) {

		super(pOwner);
		init(pDownloadJobManager);
	}

	private void init(AddDownloadJobCapable pDownloadJobManager) {
		mDownloadJobManager = pDownloadJobManager;
		initComponents();
	}

	public void loadJob(SerializableJobPackage pJobList) {
		this.editDownloadJobGroupPanel.loadJob(pJobList);
	}

	private void saveDownloadTemplate() {
		SerializableJobPackage downloadJobList = this.editDownloadJobGroupPanel
				.buildJob();
		if (downloadJobList == null)
			return;

		EditDownloadJobHelper helper = new EditDownloadJobHelper(this);
		helper.saveDownloadTemplate(downloadJobList);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		editDownloadJobGroupPanel = new de.phleisch.app.itsucks.gui.job.panel.EditDownloadJobGroupPanel();
		buttonPanel = new javax.swing.JPanel();
		startButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Edit download job");
		setLocationByPlatform(true);

		startButton.setText("Start download");
		startButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startButtonActionPerformed(evt);
			}
		});
		buttonPanel.add(startButton);

		saveButton.setText("Save as template");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveButtonActionPerformed(evt);
			}
		});
		buttonPanel.add(saveButton);

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});
		buttonPanel.add(cancelButton);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				editDownloadJobGroupPanel,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 622,
				Short.MAX_VALUE).add(buttonPanel,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 622,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(editDownloadJobGroupPanel,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 649,
						Short.MAX_VALUE).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(
						buttonPanel,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-FIRST:event_saveButtonActionPerformed
	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
		saveDownloadTemplate();
	}//GEN-LAST:event_saveButtonActionPerformed

	//GEN-FIRST:event_cancelButtonActionPerformed
	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	//GEN-FIRST:event_startButtonActionPerformed
	private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {

		SerializableJobPackage job = this.editDownloadJobGroupPanel.buildJob();
		if (job == null)
			return;

		DownloadJob downloadJob = (DownloadJob) job.getJobs().get(0);
		File path = downloadJob.getSavePath();
		if (!path.exists()) {
			
			JOptionPane.showMessageDialog(this, "The save path does not exists. Should it be created?",
					"Create save path?", JOptionPane.YES_NO_OPTION);
			
		} else if (!path.canWrite()) {
			
			JOptionPane.showMessageDialog(this, "The save path does not exists. Should it be created?",
					"Create save path?", JOptionPane.YES_NO_OPTION);

			
		}
		
		
		mDownloadJobManager.addDownload(job);

		this.dispose();

	}//GEN-LAST:event_startButtonActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JButton cancelButton;
	private de.phleisch.app.itsucks.gui.job.panel.EditDownloadJobGroupPanel editDownloadJobGroupPanel;
	private javax.swing.JButton saveButton;
	private javax.swing.JButton startButton;
	// End of variables declaration//GEN-END:variables

}