//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.24 at 07:08:28 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.phleisch.app.itsucks.persistence.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.phleisch.app.itsucks.persistence.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SerializedHttpRetrieverConfiguration }
     * 
     */
    public SerializedHttpRetrieverConfiguration createSerializedHttpRetrieverConfiguration() {
        return new SerializedHttpRetrieverConfiguration();
    }

    /**
     * Create an instance of {@link SerializedHttpResponseCodeBehaviourHostConfig }
     * 
     */
    public SerializedHttpResponseCodeBehaviourHostConfig createSerializedHttpResponseCodeBehaviourHostConfig() {
        return new SerializedHttpResponseCodeBehaviourHostConfig();
    }

    /**
     * Create an instance of {@link SerializedJobParameter }
     * 
     */
    public SerializedJobParameter createSerializedJobParameter() {
        return new SerializedJobParameter();
    }

    /**
     * Create an instance of {@link SerializedDownloadJob }
     * 
     */
    public SerializedDownloadJob createSerializedDownloadJob() {
        return new SerializedDownloadJob();
    }

    /**
     * Create an instance of {@link SerializedHttpAuthenticationFilter }
     * 
     */
    public SerializedHttpAuthenticationFilter createSerializedHttpAuthenticationFilter() {
        return new SerializedHttpAuthenticationFilter();
    }

    /**
     * Create an instance of {@link SerializedHttpRetrieverResponseCodeBehaviour }
     * 
     */
    public SerializedHttpRetrieverResponseCodeBehaviour createSerializedHttpRetrieverResponseCodeBehaviour() {
        return new SerializedHttpRetrieverResponseCodeBehaviour();
    }

    /**
     * Create an instance of {@link SerializedFileSizeFilter }
     * 
     */
    public SerializedFileSizeFilter createSerializedFileSizeFilter() {
        return new SerializedFileSizeFilter();
    }

    /**
     * Create an instance of {@link SerializedDownloadJobFilter }
     * 
     */
    public SerializedDownloadJobFilter createSerializedDownloadJobFilter() {
        return new SerializedDownloadJobFilter();
    }

    /**
     * Create an instance of {@link SerializedCookie }
     * 
     */
    public SerializedCookie createSerializedCookie() {
        return new SerializedCookie();
    }

    /**
     * Create an instance of {@link SerializedCookieFilter }
     * 
     */
    public SerializedCookieFilter createSerializedCookieFilter() {
        return new SerializedCookieFilter();
    }

    /**
     * Create an instance of {@link SerializedDispatcherConfiguration }
     * 
     */
    public SerializedDispatcherConfiguration createSerializedDispatcherConfiguration() {
        return new SerializedDispatcherConfiguration();
    }

    /**
     * Create an instance of {@link SerializedContentFilterConfig }
     * 
     */
    public SerializedContentFilterConfig createSerializedContentFilterConfig() {
        return new SerializedContentFilterConfig();
    }

    /**
     * Create an instance of {@link SerializedJobs }
     * 
     */
    public SerializedJobs createSerializedJobs() {
        return new SerializedJobs();
    }

    /**
     * Create an instance of {@link SerializedRegExpJobFilterRule }
     * 
     */
    public SerializedRegExpJobFilterRule createSerializedRegExpJobFilterRule() {
        return new SerializedRegExpJobFilterRule();
    }

    /**
     * Create an instance of {@link SerializedContextParameter }
     * 
     */
    public SerializedContextParameter createSerializedContextParameter() {
        return new SerializedContextParameter();
    }

    /**
     * Create an instance of {@link SerializedRegExpJobFilterAction }
     * 
     */
    public SerializedRegExpJobFilterAction createSerializedRegExpJobFilterAction() {
        return new SerializedRegExpJobFilterAction();
    }

    /**
     * Create an instance of {@link SerializedMaxLinksToFollowFilter }
     * 
     */
    public SerializedMaxLinksToFollowFilter createSerializedMaxLinksToFollowFilter() {
        return new SerializedMaxLinksToFollowFilter();
    }

    /**
     * Create an instance of {@link SerializedContentFilter }
     * 
     */
    public SerializedContentFilter createSerializedContentFilter() {
        return new SerializedContentFilter();
    }

    /**
     * Create an instance of {@link SerializedCredentials }
     * 
     */
    public SerializedCredentials createSerializedCredentials() {
        return new SerializedCredentials();
    }

    /**
     * Create an instance of {@link SerializedTimeLimitFilter }
     * 
     */
    public SerializedTimeLimitFilter createSerializedTimeLimitFilter() {
        return new SerializedTimeLimitFilter();
    }

    /**
     * Create an instance of {@link SerializedChangeHttpResponseCodeBehaviourFilter }
     * 
     */
    public SerializedChangeHttpResponseCodeBehaviourFilter createSerializedChangeHttpResponseCodeBehaviourFilter() {
        return new SerializedChangeHttpResponseCodeBehaviourFilter();
    }

    /**
     * Create an instance of {@link SerializedRegExpJobFilter }
     * 
     */
    public SerializedRegExpJobFilter createSerializedRegExpJobFilter() {
        return new SerializedRegExpJobFilter();
    }

}
