//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.03 at 10:57:57 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.phleisch.app.itsucks.persistence.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.phleisch.app.itsucks.persistence.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SerializedDownloadJob }
     * 
     */
    public SerializedDownloadJob createSerializedDownloadJob() {
        return new SerializedDownloadJob();
    }

    /**
     * Create an instance of {@link SerializedDownloadJobs }
     * 
     */
    public SerializedDownloadJobs createSerializedDownloadJobs() {
        return new SerializedDownloadJobs();
    }

}
