//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.22 at 10:37:28 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://itsucks.sourceforge.net/ItSucksJobSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.phleisch.app.itsucks.persistence.jaxb;
