//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.24 at 08:54:22 PM GMT 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hostname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://itsucks.sourceforge.net/ItSucksJobSchema}serializedHttpRetrieverResponseCodeBehaviour"/>
 *         &lt;element name="queueBehaviour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostname",
    "serializedHttpRetrieverResponseCodeBehaviour",
    "queueBehaviour"
})
@XmlRootElement(name = "serializedHttpResponseCodeBehaviourHostConfig")
public class SerializedHttpResponseCodeBehaviourHostConfig {

    @XmlElement(required = true)
    protected String hostname;
    @XmlElement(required = true)
    protected SerializedHttpRetrieverResponseCodeBehaviour serializedHttpRetrieverResponseCodeBehaviour;
    @XmlElement(required = true, nillable = true)
    protected String queueBehaviour;

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the serializedHttpRetrieverResponseCodeBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link SerializedHttpRetrieverResponseCodeBehaviour }
     *     
     */
    public SerializedHttpRetrieverResponseCodeBehaviour getSerializedHttpRetrieverResponseCodeBehaviour() {
        return serializedHttpRetrieverResponseCodeBehaviour;
    }

    /**
     * Sets the value of the serializedHttpRetrieverResponseCodeBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerializedHttpRetrieverResponseCodeBehaviour }
     *     
     */
    public void setSerializedHttpRetrieverResponseCodeBehaviour(SerializedHttpRetrieverResponseCodeBehaviour value) {
        this.serializedHttpRetrieverResponseCodeBehaviour = value;
    }

    /**
     * Gets the value of the queueBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueueBehaviour() {
        return queueBehaviour;
    }

    /**
     * Sets the value of the queueBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueueBehaviour(String value) {
        this.queueBehaviour = value;
    }

}
