//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.07 at 12:13:31 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://itsucks.sourceforge.net/ItSucksJobSchema}serializedJobFilter">
 *       &lt;sequence>
 *         &lt;element name="maxLinksToFollow" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxLinksToFollow"
})
@XmlRootElement(name = "serializedMaxLinksToFollowFilter")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
public class SerializedMaxLinksToFollowFilter
    extends SerializedJobFilter
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected int maxLinksToFollow;

    /**
     * Gets the value of the maxLinksToFollow property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public int getMaxLinksToFollow() {
        return maxLinksToFollow;
    }

    /**
     * Sets the value of the maxLinksToFollow property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setMaxLinksToFollow(int value) {
        this.maxLinksToFollow = value;
    }

}
