//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.03 at 10:57:57 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serializedJob complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serializedJob">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serializedJob", propOrder = {
    "name",
    "state",
    "priority"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
public abstract class SerializedJob {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected String name;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected BigInteger state;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected BigInteger priority;
    @XmlAttribute
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected BigInteger id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public BigInteger getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setState(BigInteger value) {
        this.state = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-03T10:57:57+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setId(BigInteger value) {
        this.id = value;
    }

}
