//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.05 at 10:13:48 PM GMT 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseCodeFrom" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="responseCodeTo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timeToWaitBetweenRetry" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseCodeFrom",
    "responseCodeTo",
    "action",
    "priority",
    "timeToWaitBetweenRetry"
})
@XmlRootElement(name = "serializedHttpRetrieverResponseCodeBehaviour")
public class SerializedHttpRetrieverResponseCodeBehaviour {

    protected int responseCodeFrom;
    protected int responseCodeTo;
    @XmlElement(required = true)
    protected String action;
    protected int priority;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long timeToWaitBetweenRetry;

    /**
     * Gets the value of the responseCodeFrom property.
     * 
     */
    public int getResponseCodeFrom() {
        return responseCodeFrom;
    }

    /**
     * Sets the value of the responseCodeFrom property.
     * 
     */
    public void setResponseCodeFrom(int value) {
        this.responseCodeFrom = value;
    }

    /**
     * Gets the value of the responseCodeTo property.
     * 
     */
    public int getResponseCodeTo() {
        return responseCodeTo;
    }

    /**
     * Sets the value of the responseCodeTo property.
     * 
     */
    public void setResponseCodeTo(int value) {
        this.responseCodeTo = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

    /**
     * Gets the value of the timeToWaitBetweenRetry property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeToWaitBetweenRetry() {
        return timeToWaitBetweenRetry;
    }

    /**
     * Sets the value of the timeToWaitBetweenRetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeToWaitBetweenRetry(Long value) {
        this.timeToWaitBetweenRetry = value;
    }

}
