//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.07 at 12:13:31 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://itsucks.sourceforge.net/ItSucksJobSchema}serializedJob">
 *       &lt;sequence>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentJobId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxRetryCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minTimeBetweenRetry" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="saveToFile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="savePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "url",
    "parentJobId",
    "depth",
    "maxRetryCount",
    "minTimeBetweenRetry",
    "saveToFile",
    "savePath"
})
@XmlRootElement(name = "serializedDownloadJob")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
public class SerializedDownloadJob
    extends SerializedJob
{

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected String url;
    @XmlElement(required = true, type = Long.class, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected Long parentJobId;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected int depth;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected int maxRetryCount;
    @XmlElement(required = true, type = Long.class, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected Long minTimeBetweenRetry;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected boolean saveToFile;
    @XmlElement(required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected String savePath;

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the parentJobId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public Long getParentJobId() {
        return parentJobId;
    }

    /**
     * Sets the value of the parentJobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setParentJobId(Long value) {
        this.parentJobId = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public int getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setDepth(int value) {
        this.depth = value;
    }

    /**
     * Gets the value of the maxRetryCount property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public int getMaxRetryCount() {
        return maxRetryCount;
    }

    /**
     * Sets the value of the maxRetryCount property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setMaxRetryCount(int value) {
        this.maxRetryCount = value;
    }

    /**
     * Gets the value of the minTimeBetweenRetry property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public Long getMinTimeBetweenRetry() {
        return minTimeBetweenRetry;
    }

    /**
     * Sets the value of the minTimeBetweenRetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setMinTimeBetweenRetry(Long value) {
        this.minTimeBetweenRetry = value;
    }

    /**
     * Gets the value of the saveToFile property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public boolean isSaveToFile() {
        return saveToFile;
    }

    /**
     * Sets the value of the saveToFile property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setSaveToFile(boolean value) {
        this.saveToFile = value;
    }

    /**
     * Gets the value of the savePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public String getSavePath() {
        return savePath;
    }

    /**
     * Sets the value of the savePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setSavePath(String value) {
        this.savePath = value;
    }

}
