//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.03 at 11:31:10 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workerThreads" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dispatchDelay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workerThreads",
    "dispatchDelay"
})
@XmlRootElement(name = "serializedDispatcherConfiguration")
public class SerializedDispatcherConfiguration {

    protected int workerThreads;
    protected int dispatchDelay;

    /**
     * Gets the value of the workerThreads property.
     * 
     */
    public int getWorkerThreads() {
        return workerThreads;
    }

    /**
     * Sets the value of the workerThreads property.
     * 
     */
    public void setWorkerThreads(int value) {
        this.workerThreads = value;
    }

    /**
     * Gets the value of the dispatchDelay property.
     * 
     */
    public int getDispatchDelay() {
        return dispatchDelay;
    }

    /**
     * Sets the value of the dispatchDelay property.
     * 
     */
    public void setDispatchDelay(int value) {
        this.dispatchDelay = value;
    }

}
