//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.07 at 12:13:31 PM CEST 
//


package de.phleisch.app.itsucks.persistence.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://itsucks.sourceforge.net/ItSucksJobSchema}serializedJobFilter">
 *       &lt;sequence>
 *         &lt;element name="allowOnlyRelativeReferences" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maxRecursionDepth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allowedHostName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="saveToFileFilter" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="alreadyAddedUri" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allowOnlyRelativeReferences",
    "maxRecursionDepth",
    "baseUrl",
    "allowedHostName",
    "saveToFileFilter",
    "alreadyAddedUri"
})
@XmlRootElement(name = "serializedDownloadJobFilter")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
public class SerializedDownloadJobFilter
    extends SerializedJobFilter
{

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected boolean allowOnlyRelativeReferences;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected int maxRecursionDepth;
    @XmlElement(required = true, nillable = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected String baseUrl;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected List<String> allowedHostName;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected List<String> saveToFileFilter;
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    protected List<String> alreadyAddedUri;

    /**
     * Gets the value of the allowOnlyRelativeReferences property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public boolean isAllowOnlyRelativeReferences() {
        return allowOnlyRelativeReferences;
    }

    /**
     * Sets the value of the allowOnlyRelativeReferences property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setAllowOnlyRelativeReferences(boolean value) {
        this.allowOnlyRelativeReferences = value;
    }

    /**
     * Gets the value of the maxRecursionDepth property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public int getMaxRecursionDepth() {
        return maxRecursionDepth;
    }

    /**
     * Sets the value of the maxRecursionDepth property.
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setMaxRecursionDepth(int value) {
        this.maxRecursionDepth = value;
    }

    /**
     * Gets the value of the baseUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * Sets the value of the baseUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public void setBaseUrl(String value) {
        this.baseUrl = value;
    }

    /**
     * Gets the value of the allowedHostName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedHostName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedHostName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public List<String> getAllowedHostName() {
        if (allowedHostName == null) {
            allowedHostName = new ArrayList<String>();
        }
        return this.allowedHostName;
    }

    /**
     * Gets the value of the saveToFileFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saveToFileFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSaveToFileFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public List<String> getSaveToFileFilter() {
        if (saveToFileFilter == null) {
            saveToFileFilter = new ArrayList<String>();
        }
        return this.saveToFileFilter;
    }

    /**
     * Gets the value of the alreadyAddedUri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alreadyAddedUri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlreadyAddedUri().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2007-07-07T12:13:31+02:00", comments = "JAXB RI v2.0.5-b02-fcs")
    public List<String> getAlreadyAddedUri() {
        if (alreadyAddedUri == null) {
            alreadyAddedUri = new ArrayList<String>();
        }
        return this.alreadyAddedUri;
    }

}
