  </div>

  <div class="footer">
  <!--
    <div style="float: left;">
      <a href="http://www.webcounter.goweb.de"><img src="http://webcounter.goweb.de/51650.GIF" alt="gratis Counter by GOWEB" border="0" vspace="0"></a><br>
    </div>
  
    <a style="float: right;" href="http://sourceforge.net"><img src=
    "http://sflogo.sourceforge.net/sflogo.php?group_id=186141&amp;type=1" width="88" height="31" border="0" alt="SourceForge.net Logo" /></a>
  --> 
    <span>Last edited June 17th, 2007<br />by Oliver Mihatsch</span>     
  </div>
</body>
</html>