  </div>
  <div class="footer">
  <!-- 
    <div style="float: left;padding:5px 0px">
      <a href="http://www.dreamcounter.de" target="_top"><img
      border="0" title="kostenloser Dreamcounter" alt="Counter"
      src="http://dreamcounter.de/dc11816.gif"></a>          
    </div>
  
    <a style="float: right;" href="http://sourceforge.net"><img src=
    "http://sflogo.sourceforge.net/sflogo.php?group_id=186141&amp;type=1" width="88" height="31" border="0" alt="SourceForge.net Logo" /></a>
    <span>Last edited September 15th, 2008<br />by Oliver Mihatsch</span>
  </div>
   -->
</body>
</html>