  </div>
  
  <div id="footer">
  	<div id="footerBackground">
    <div id="counter" style="float: left;">
    
      <a href="http://www.dreamcounter.de" target="_top"><img
      border="0" title="kostenloser Dreamcounter" alt="Counter"
      src="http://dreamcounter.de/dc11816.gif"/></a>
     
    </div>
    <a style="float: right;" href="http://sourceforge.net"><img src=
    "http://sflogo.sourceforge.net/sflogo.php?group_id=1861410000&amp;type=1" width="88" height="31" border="0" alt="SourceForge.net Logo" /></a>
    
    <div class="footerText">
    	Last edited May 30th, 2010 by Oliver Mihatsch,
    	Design by <a href="http://pierini.de">Anna Pierini</a>
    </div>
    <div>
  </div>
  
  </div> <!-- content Area -->
  </div> <!-- right border --> 
  </div> <!-- left border -->
  
  
  </div> <!-- page -->
</body>
</html>