/*
 * QueueDownloadJobOverview.java
 *
 * Created on __DATE__, __TIME__
 */

package de.phleisch.app.itsucks.gui2.panel;

import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;

import de.phleisch.app.itsucks.DispatcherThread;
import de.phleisch.app.itsucks.Job;
import de.phleisch.app.itsucks.event.CoreEvents;
import de.phleisch.app.itsucks.event.DefaultEventFilter;
import de.phleisch.app.itsucks.event.Event;
import de.phleisch.app.itsucks.event.EventObserver;
import de.phleisch.app.itsucks.event.JobEvent;
import de.phleisch.app.itsucks.io.DownloadJob;

/**
 *
 * @author  __USER__
 */
public class DownloadJobQueueOverviewPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 2406761069696757338L;
	private DispatcherThread mJobDispatcher;
	private EventObserver mEventObserver = new JobEventObserver();
	
	/** Creates new form QueueDownloadJobOverview */
	public DownloadJobQueueOverviewPanel() {
		initComponents();
	}

	public void setDispatcher(DispatcherThread pDispatcher) {
		mJobDispatcher = pDispatcher;

		DefaultEventFilter eventFilter = new DefaultEventFilter();
		eventFilter.addAllowedCategory(CoreEvents.EVENT_CATEGORY_JOB);
		eventFilter.addAllowedCategory(CoreEvents.EVENT_CATEGORY_JOBMANAGER);
		
		mJobDispatcher.getEventManager().registerObserver(mEventObserver, eventFilter);
	}

	public DispatcherThread getDispatcher() {
		return mJobDispatcher;
	}

	public void removeDispatcher() {
		mJobDispatcher.getEventManager().unregisterObserver(mEventObserver);
		
		downloadJobStatusTableAllPanel.shutdown();
		downloadJobStatusTableRunningPanel.shutdown();
		downloadJobStatusTableOpenPanel.shutdown();
		downloadJobStatusTableFinishedPanel.shutdown();
		
		mJobDispatcher = null;
	}
	
	private void addDownloadJob(DownloadJob pJob) {
			
		List<DownloadJobStatusTablePanel> panels = getPanelsForState(Job.STATE_OPEN);
		for (DownloadJobStatusTablePanel panel : panels) {
			panel.addDownloadJob(pJob);
		}
	}
	
	private void removeDownloadJob(DownloadJob pJob) {
		
		List<DownloadJobStatusTablePanel> panels = getPanelsForState(pJob.getState());
		for (DownloadJobStatusTablePanel panel : panels) {
			panel.removeDownloadJob(pJob);
		}
	}
	
	private void moveDownloadJob(DownloadJob pJob, int pOldState, int pNewState) {
		
		List<DownloadJobStatusTablePanel> oldPanels = getPanelsForState(pOldState);
		List<DownloadJobStatusTablePanel> newPanels = getPanelsForState(pNewState);

		for (DownloadJobStatusTablePanel oldPanel : oldPanels) {
//			if(!newPanels.contains(oldPanel)) {
				oldPanel.removeDownloadJob(pJob);
//			}
		}
		
		for (DownloadJobStatusTablePanel newPanel : newPanels) {
//			if(!oldPanels.contains(newPanel)) {
				newPanel.addDownloadJob(pJob);
//			}
		}
	}

	private List<DownloadJobStatusTablePanel> getPanelsForState(int pState) {
		
		List<DownloadJobStatusTablePanel> panels = new ArrayList<DownloadJobStatusTablePanel>();
		
		panels.add(downloadJobStatusTableAllPanel);
		
		switch (pState) {

		case Job.STATE_OPEN:
			panels.add(downloadJobStatusTableOpenPanel);
			break;
			
		case Job.STATE_ASSIGNED:
		case Job.STATE_IN_PROGRESS:
			panels.add(downloadJobStatusTableRunningPanel);
			break;
		
		case Job.STATE_CLOSED:
		case Job.STATE_ERROR:
		case Job.STATE_FAILED:
		case Job.STATE_FINISHED:
		case Job.STATE_IGNORED:
		case Job.STATE_ALREADY_PROCESSED:
			panels.add(downloadJobStatusTableFinishedPanel);
			break;
			
		default: 
			throw new IllegalStateException("Unknown state: " + pState);
			
		}
		
		return panels;
	}
	
	private class JobEventObserver implements EventObserver {

		public void processEvent(Event pEvent) {
			
			JobEvent jobEvent = (JobEvent) pEvent;
			DownloadJob job = (DownloadJob) jobEvent.getJob();

			if(jobEvent.getType() == CoreEvents.EVENT_JOB_CHANGED.getType()) {
				
				PropertyChangeEvent propertyChangeEvent = jobEvent.getPropertyChangeEvent();
				
				if(Job.JOB_STATE_PROPERTY.equals(propertyChangeEvent.getPropertyName())) {
					moveDownloadJob(job, 
						(Integer)propertyChangeEvent.getOldValue(), 
						(Integer)propertyChangeEvent.getNewValue());
				}
				
			} else if(jobEvent.getType() == CoreEvents.EVENT_JOBMANAGER_JOB_ADDED.getType()) {
				
				addDownloadJob(job);
				
			} else if(jobEvent.getType() == CoreEvents.EVENT_JOBMANAGER_JOB_REMOVED.getType()) {
				
				removeDownloadJob(job);
				
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jTabbedPane1 = new javax.swing.JTabbedPane();
		downloadJobStatusTableAllPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel();
		downloadJobStatusTableRunningPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel();
		downloadJobStatusTableOpenPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel();
		downloadJobStatusTableFinishedPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel();
		infoPanel = new javax.swing.JPanel();

		jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
		jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 12));
		jTabbedPane1.addTab("All", downloadJobStatusTableAllPanel);

		jTabbedPane1.addTab("Running", downloadJobStatusTableRunningPanel);

		jTabbedPane1.addTab("Open", downloadJobStatusTableOpenPanel);

		jTabbedPane1.addTab("Finished", downloadJobStatusTableFinishedPanel);

		org.jdesktop.layout.GroupLayout infoPanelLayout = new org.jdesktop.layout.GroupLayout(
				infoPanel);
		infoPanel.setLayout(infoPanelLayout);
		infoPanelLayout.setHorizontalGroup(infoPanelLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 584,
				Short.MAX_VALUE));
		infoPanelLayout.setVerticalGroup(infoPanelLayout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 445,
				Short.MAX_VALUE));
		jTabbedPane1.addTab("Info", infoPanel);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jTabbedPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 589,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jTabbedPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 472,
				Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel downloadJobStatusTableAllPanel;
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel downloadJobStatusTableFinishedPanel;
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel downloadJobStatusTableOpenPanel;
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobStatusTablePanel downloadJobStatusTableRunningPanel;
	private javax.swing.JPanel infoPanel;
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

}