/* Copyright (C) 2006-2007 Oliver Mihatsch (banishedknight@users.sf.net)
 * This is free software distributed under the terms of the
 * GNU Public License.  See the file COPYING for details. 
 *
 * olli
 * Created on 26.08.2007
 */
package de.phleisch.app.itsucks.gui2.panel;

/**
 *
 * @author  olli
 */
public class DownloadJobBasicPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 6676129664345121404L;

	/** Creates new form DownloadJobMainPanel */
	public DownloadJobBasicPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabelName = new javax.swing.JLabel();
		jTextFieldName = new javax.swing.JTextField();
		jLabelURL = new javax.swing.JLabel();
		jTextFieldURL = new javax.swing.JTextField();
		jLabelSavePath = new javax.swing.JLabel();
		jTextFieldSavePath = new javax.swing.JTextField();
		jButtonSavePath = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jTextField5 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jCheckBox2 = new javax.swing.JCheckBox();

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Basic Parameters"));
		jLabelName.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabelName.setText("Name:");

		jLabelURL.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabelURL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabelURL.setText("Start URL:");

		jLabelSavePath.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabelSavePath.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabelSavePath.setText("Save path:");

		jButtonSavePath.setText("Browse");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jLabelSavePath)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jLabelURL)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																jLabelName))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jTextFieldURL,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																355,
																Short.MAX_VALUE)
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jTextFieldSavePath,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				269,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jButtonSavePath))
														.add(
																jPanel1Layout
																		.createSequentialGroup()
																		.add(
																				jTextFieldName,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				151,
																				Short.MAX_VALUE)
																		.add(
																				204,
																				204,
																				204)))
										.addContainerGap()));

		jPanel1Layout.linkSize(new java.awt.Component[] { jLabelName,
				jLabelSavePath, jLabelURL },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabelName)
														.add(
																jTextFieldName,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabelURL)
														.add(
																jTextFieldURL,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabelSavePath)
														.add(
																jTextFieldSavePath,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jButtonSavePath))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Connection Settings"));
		jLabel1.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("Working Threads:");

		jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("Max. connections per server:");

		jTextField1.setText("jTextField1");

		jTextField2.setText("jTextField2");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel2).add(
																jLabel1))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jTextField2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(191, Short.MAX_VALUE)));

		jPanel2Layout.linkSize(new java.awt.Component[] { jLabel1, jLabel2 },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel1)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jTextField2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel2))
										.addContainerGap(16, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Proxy Settings"));
		jPanel3.setEnabled(false);
		jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("Server:");
		jLabel3.setEnabled(false);

		jTextField3.setText("jTextField3");
		jTextField3.setEnabled(false);

		jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("Port:");
		jLabel4.setEnabled(false);

		jTextField4.setText("jTextField4");
		jTextField4.setEnabled(false);

		jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel5.setText("User:");
		jLabel5.setEnabled(false);

		jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 12));
		jCheckBox1.setText("Enable authentication");
		jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox1.setEnabled(false);
		jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jTextField5.setText("jTextField5");
		jTextField5.setEnabled(false);

		jLabel6.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel6.setText("Password:");
		jLabel6.setEnabled(false);

		jTextField6.setText("jTextField6");
		jTextField6.setEnabled(false);

		jCheckBox2.setFont(new java.awt.Font("Dialog", 0, 12));
		jCheckBox2.setText("Enable Proxy");
		jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0,
				0, 0));
		jCheckBox2.setEnabled(false);
		jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel3Layout
																		.createSequentialGroup()
																		.add(
																				jLabel3)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				130,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jLabel4)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				122,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																jPanel3Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(
																				jPanel3Layout
																						.createSequentialGroup()
																						.add(
																								jLabel5)
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED)
																						.add(
																								jTextField5,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								130,
																								Short.MAX_VALUE)
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED)
																						.add(
																								jLabel6)
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED)
																						.add(
																								jTextField6,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								117,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.add(
																				jPanel3Layout
																						.createSequentialGroup()
																						.add(
																								jCheckBox1)
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED,
																								255,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
														.add(
																jPanel3Layout
																		.createSequentialGroup()
																		.add(
																				jCheckBox2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				107,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED,
																				288,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.add(44, 44, 44)));

		jPanel3Layout.linkSize(new java.awt.Component[] { jTextField3,
				jTextField4, jTextField5, jTextField6 },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel3Layout.linkSize(new java.awt.Component[] { jLabel4, jLabel6 },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel3Layout.linkSize(new java.awt.Component[] { jLabel3, jLabel5 },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jCheckBox2)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3)
														.add(
																jTextField3,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel4)
														.add(
																jTextField4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jCheckBox1)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel5)
														.add(jLabel6)
														.add(
																jTextField6,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jTextField5,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap().add(
						layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.TRAILING).add(
								org.jdesktop.layout.GroupLayout.LEADING,
								jPanel3,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).add(
								org.jdesktop.layout.GroupLayout.LEADING,
								jPanel2,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).add(
								org.jdesktop.layout.GroupLayout.LEADING,
								jPanel1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(jPanel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jPanel2,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jPanel3,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonSavePath;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabelName;
	private javax.swing.JLabel jLabelSavePath;
	private javax.swing.JLabel jLabelURL;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextFieldName;
	private javax.swing.JTextField jTextFieldSavePath;
	private javax.swing.JTextField jTextFieldURL;
	// End of variables declaration//GEN-END:variables

}