/*
 * EditDownloadJobGroupPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package de.phleisch.app.itsucks.gui2.panel;

import java.util.List;

import javax.swing.JList;

import de.phleisch.app.itsucks.filter.DownloadJobFilter;
import de.phleisch.app.itsucks.filter.JobFilter;
import de.phleisch.app.itsucks.filter.MaxLinksToFollowFilter;
import de.phleisch.app.itsucks.filter.RegExpJobFilter;
import de.phleisch.app.itsucks.filter.RegExpJobFilter.RegExpFilterRule;
import de.phleisch.app.itsucks.gui.panel.ExtendedListModel;
import de.phleisch.app.itsucks.io.DownloadJob;

/**
 *
 * @author  __USER__
 */
public class EditDownloadJobGroupPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 8250877774474103209L;
	
	/** Creates new form EditDownloadJobGroupPanel */
	public EditDownloadJobGroupPanel() {
		initComponents();
	}
	
	public void loadJob(DownloadJob pJob, List<JobFilter> pFilters) {
		
		DownloadJobFilter downloadJobFilter = null;
		MaxLinksToFollowFilter maxLinksToFollowFilter = null;
		RegExpJobFilter regExpJobFilter = null;
		
		for (JobFilter jobFilter : pFilters) {
			if(jobFilter instanceof DownloadJobFilter) {
				downloadJobFilter = (DownloadJobFilter) jobFilter;
				continue;
			}
			if(jobFilter instanceof MaxLinksToFollowFilter) {
				maxLinksToFollowFilter = (MaxLinksToFollowFilter) jobFilter;
				continue;
			}
			if(jobFilter instanceof RegExpJobFilter) {
				regExpJobFilter = (RegExpJobFilter) jobFilter;
				continue;
			}
		}
		
		//load basic panel
		this.downloadJobBasicPanel.nameTextField.setText(pJob.getName());
		this.downloadJobBasicPanel.urlTextField.setText(pJob.getUrl().toExternalForm());
		this.downloadJobBasicPanel.savePathTextField.setText(
				pJob.getSavePath().getAbsolutePath());
		this.downloadJobBasicPanel.maxRetriesTextField.setText(
				String.valueOf(pJob.getMaxRetryCount()));
		
		//load simple rules
		if(maxLinksToFollowFilter != null) {
			this.downloadJobSimpleRulesPanel.linksToFollowTextField.setText(
					String.valueOf(maxLinksToFollowFilter.getMaxLinksToFollow()));
		}
		this.downloadJobSimpleRulesPanel.recursionDepthTextField.setText(
				String.valueOf(pJob.getDepth()));
		if(downloadJobFilter != null) {
			
			if(downloadJobFilter.isAllowOnlyRelativeReferences()) {
				this.downloadJobSimpleRulesPanel.urlPrefixCheckBox.setSelected(true);
				this.downloadJobSimpleRulesPanel.urlPrefixTextField.setText(
						downloadJobFilter.getBaseURL().toExternalForm());
			} else {
				this.downloadJobSimpleRulesPanel.urlPrefixCheckBox.setSelected(false);
			}
			
			this.downloadJobSimpleRulesPanel.hostnameFilterTableModel.setRowCount(0);
			String[] allowedHostNames = downloadJobFilter.getAllowedHostNames();
			for (String string : allowedHostNames) {
				this.downloadJobSimpleRulesPanel.hostnameFilterTableModel.addRow(
						new Object[] {string});
			}

			this.downloadJobSimpleRulesPanel.saveToDiskFilterTabelModel.setRowCount(0);
			String[] saveToDiskFilter = downloadJobFilter.getSaveToFileFilter();
			for (String string : saveToDiskFilter) {
				this.downloadJobSimpleRulesPanel.saveToDiskFilterTabelModel.addRow(
						new Object[] {string});
			}
			
		}
		
		//load advanced rules
		ExtendedListModel model = new ExtendedListModel();
		this.downloadJobAdvancedRulesPanel.advancedFilterList.setModel(model);
		for (RegExpFilterRule jobFilterRule : regExpJobFilter.getFilterRules()) {
			model.addElement(jobFilterRule);
		}
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		tabbedPane = new javax.swing.JTabbedPane();
		downloadJobBasicPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobBasicPanel();
		downloadJobSimpleRulesPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobSimpleRulesPanel();
		downloadJobAdvancedRulesPanel = new de.phleisch.app.itsucks.gui2.panel.DownloadJobAdvancedRulesPanel();

		tabbedPane.addTab("Basic Parameters", downloadJobBasicPanel);

		tabbedPane.addTab("Simple Rules", downloadJobSimpleRulesPanel);

		tabbedPane.addTab("Advanced Rules", downloadJobAdvancedRulesPanel);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(tabbedPane,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 619,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(tabbedPane,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587,
				Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobAdvancedRulesPanel downloadJobAdvancedRulesPanel;
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobBasicPanel downloadJobBasicPanel;
	private de.phleisch.app.itsucks.gui2.panel.DownloadJobSimpleRulesPanel downloadJobSimpleRulesPanel;
	private javax.swing.JTabbedPane tabbedPane;
	// End of variables declaration//GEN-END:variables

}