/*
 * DownloadJobCookieSettings.java
 *
 * Created on 1. Mai 2008, 17:13
 */

package de.phleisch.app.itsucks.gui.job.panel;

import java.util.List;

import de.phleisch.app.itsucks.filter.download.http.impl.Cookie;
import de.phleisch.app.itsucks.filter.download.http.impl.CookieFilter;
import de.phleisch.app.itsucks.gui.common.panel.EditListCallbackPanel;
import de.phleisch.app.itsucks.gui.common.panel.EditListPanel;
import de.phleisch.app.itsucks.gui.common.panel.EditListPanel.ListElement;
import de.phleisch.app.itsucks.gui.job.ifc.EditJobCapable;
import de.phleisch.app.itsucks.gui.util.ExtendedListModel;
import de.phleisch.app.itsucks.gui.util.SwingUtils;
import de.phleisch.app.itsucks.persistence.SerializableJobPackage;

/**
 *
 * @author  olli
 */
public class DownloadJobCookieSettings extends javax.swing.JPanel implements EditJobCapable {
    
	private static final long serialVersionUID = 7000553342079429183L;

	/** Creates new form DownloadJobCookieSettings */
    public DownloadJobCookieSettings() {
        initComponents();
        initListPanel();
    }

	private void initListPanel() {
		
        EditListCallback editListCallback = new EditListCallback();
        editListCallback.enableEditArea(false);
		this.cookieListPane
			.setLogic(editListCallback);

		this.cookieListPane
				.registerDataField(nameTextField);
		this.cookieListPane
				.registerDataField(valueTextField);
		this.cookieListPane
				.registerDataField(domainTextField);
		this.cookieListPane
				.registerDataField(pathTextField);
	}    

	public void loadJobPackage(SerializableJobPackage pJobPackage) {
		
		CookieFilter cookieFilter = 
			(CookieFilter) pJobPackage.getFilterByType(CookieFilter.class);
		
		if(cookieFilter != null) {
			
			ExtendedListModel model = this.cookieListPane.getListModel();
			for (Cookie cookie : cookieFilter.getCookies()) {
				model.addElement(this.new CookieListElement(cookie));
			}
		}
	}

	public void saveJobPackage(SerializableJobPackage pJobPackage) {
		
		CookieFilter cookieFilter = 
			(CookieFilter) pJobPackage.getFilterByType(CookieFilter.class);
		
		ExtendedListModel listModel = this.cookieListPane.getListModel();
		if(listModel.size() > 0) {
		
			if(cookieFilter == null) {
				cookieFilter = new CookieFilter();
				pJobPackage.addFilter(cookieFilter);
			}
		
			Object[] elements = listModel.toArray();
			for (int i = 0; i < elements.length; i++) {
				CookieListElement element = (CookieListElement) elements[i];
				cookieFilter.addCookie(element);
			}
		}
	}

	public List<String> validateFields() {
		// TODO Auto-generated method stub
		return null;
	}
	
	public class CookieListElement
		extends Cookie
		implements EditListPanel.ListElement {
		
		public CookieListElement() {
			super();
		}
		
		public CookieListElement(final Cookie pCookie) {
			super(pCookie);
		}
		
		@Override
		public String toString() {
			String result = "<html>Server: "
					+ getDomain() + getPath()
					+ "<br>"
					+ "Name: "
					+ getName() 
					+ "</html>";

			return result;
		}
	}
	
	protected class EditListCallback implements
		EditListCallbackPanel.EditListCallbackInterface {

		public ListElement createNewElement() {
			return new CookieListElement();
		}

		public void emptyEditArea() {
			loadEditArea(new CookieListElement());
		}

		public void enableEditArea(boolean pEnable) {
			SwingUtils.setContainerAndChildrenEnabled(
					editCookiePane, pEnable);
		}

		public void loadEditArea(ListElement pElement) {
			
			CookieListElement element = (CookieListElement) pElement;
			
			nameTextField.setText(element.getName());
			valueTextField.setText(element.getValue());
			domainTextField.setText(element.getDomain());
			pathTextField.setText(element.getPath());
		}

		public void updateListElement(ListElement pElement) {
			CookieListElement element = (CookieListElement) pElement;
			
			element.setName(nameTextField.getText());
			element.setValue(valueTextField.getText());
			element.setDomain(domainTextField.getText());
			element.setPath(pathTextField.getText());
		}
		
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cookieSettingsPane = new javax.swing.JPanel();
        cookieListPane = new de.phleisch.app.itsucks.gui.common.panel.EditListCallbackPanel();
        editCookiePane = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        domainLabel = new javax.swing.JLabel();
        domainTextField = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        cookieParserPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        cookieSettingsPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Cookie Settings"));

        editCookiePane.setBorder(javax.swing.BorderFactory.createTitledBorder("Cookie"));

        nameLabel.setText("Name:");

        valueLabel.setText("Value:");

        domainLabel.setText("Domain:");

        pathLabel.setText("Path:");

        javax.swing.GroupLayout editCookiePaneLayout = new javax.swing.GroupLayout(editCookiePane);
        editCookiePane.setLayout(editCookiePaneLayout);
        editCookiePaneLayout.setHorizontalGroup(
            editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCookiePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(domainLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valueLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addGroup(editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(valueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(domainTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addContainerGap())
        );
        editCookiePaneLayout.setVerticalGroup(
            editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCookiePaneLayout.createSequentialGroup()
                .addGroup(editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domainLabel)
                    .addComponent(domainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCookiePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathLabel)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cookieParserPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Cookie Parser"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Firefox (Mozilla)", "Internet Explorer" }));

        jLabel5.setText("Format:");

        jLabel6.setText("Data:");

        jButton1.setText("Parse Cookie String");

        javax.swing.GroupLayout cookieParserPaneLayout = new javax.swing.GroupLayout(cookieParserPane);
        cookieParserPane.setLayout(cookieParserPaneLayout);
        cookieParserPaneLayout.setHorizontalGroup(
            cookieParserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookieParserPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cookieParserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cookieParserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cookieParserPaneLayout.setVerticalGroup(
            cookieParserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cookieParserPaneLayout.createSequentialGroup()
                .addGroup(cookieParserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cookieParserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout cookieSettingsPaneLayout = new javax.swing.GroupLayout(cookieSettingsPane);
        cookieSettingsPane.setLayout(cookieSettingsPaneLayout);
        cookieSettingsPaneLayout.setHorizontalGroup(
            cookieSettingsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cookieSettingsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cookieSettingsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cookieParserPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCookiePane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cookieListPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addContainerGap())
        );
        cookieSettingsPaneLayout.setVerticalGroup(
            cookieSettingsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookieSettingsPaneLayout.createSequentialGroup()
                .addComponent(cookieListPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCookiePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cookieParserPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cookieSettingsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cookieSettingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.phleisch.app.itsucks.gui.common.panel.EditListCallbackPanel cookieListPane;
    private javax.swing.JPanel cookieParserPane;
    private javax.swing.JPanel cookieSettingsPane;
    private javax.swing.JLabel domainLabel;
    private javax.swing.JTextField domainTextField;
    private javax.swing.JPanel editCookiePane;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
    
}
