/*
 * EditDownloadJobGroupPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package de.phleisch.app.itsucks.gui.job.panel;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import de.phleisch.app.itsucks.gui.job.ifc.EditJobCapable;
import de.phleisch.app.itsucks.persistence.SerializableJobPackage;

/**
 *
 * @author  __USER__
 */
public class EditDownloadJobGroupPanel extends JPanel {

	private static final long serialVersionUID = 8250877774474103209L;

	private List<EditJobCapable> mEditJobPanels;
	
	/** Creates new form EditDownloadJobGroupPanel */
	public EditDownloadJobGroupPanel() {
		init();
	}
	
	protected void init() {
		initComponents();
		buildPanelList();
	}

	protected void buildPanelList() {
		mEditJobPanels = new ArrayList<EditJobCapable>();
		
		//basic panel
		mEditJobPanels.add(this.downloadJobBasicPanel);

		//simple rules
		mEditJobPanels.add(this.downloadJobSimpleRulesPanel);
		
		//special rules (file size filter and http status code filter) 
		mEditJobPanels.add(this.downloadJobSpecialRulesPanel);
		
		//advanced rules
		mEditJobPanels.add(this.downloadJobRegExpRulesPanel);
		
		//content filter
		mEditJobPanels.add(this.downloadJobContentFilterPanel);
	}

	public void loadJob(SerializableJobPackage pJobList) {

		for (EditJobCapable jobPanel : mEditJobPanels) {
			jobPanel.loadJobPackage(pJobList);
		}
		
	}

	public SerializableJobPackage buildJob() {

		if (!validatePanels())
			return null;

		SerializableJobPackage result = new SerializableJobPackage();
		
		for (EditJobCapable jobPanel : mEditJobPanels) {
			jobPanel.saveJobPackage(result);
		}
		
		return result;
	}

	private boolean validatePanels() {

		boolean result = true;

		for (EditJobCapable jobPanel : mEditJobPanels) {
			List<String> errors = jobPanel.validateFields();
			if(errors.size() > 0) {
				result = false;
				tabbedPane.setSelectedComponent((Component) jobPanel);
				displayErrors(errors);
				
				break;
			}
		}

		return result;
	}

	private void displayErrors(List<String> errorsBasicPanel) {
		StringBuffer buffer = new StringBuffer();
		for (String string : errorsBasicPanel) {
			buffer.append(string + '\n');
		}

		JOptionPane.showMessageDialog(this, buffer.toString(),
				"Validation errors", JOptionPane.ERROR_MESSAGE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		tabbedPane = new javax.swing.JTabbedPane();
		downloadJobBasicPanel = new de.phleisch.app.itsucks.gui.job.panel.DownloadJobBasicPanel();
		downloadJobSimpleRulesPanel = new de.phleisch.app.itsucks.gui.job.panel.DownloadJobSimpleRulesPanel();
		downloadJobSpecialRulesPanel = new de.phleisch.app.itsucks.gui.job.panel.DownloadJobFileSizeRulesPanel();
		downloadJobRegExpRulesPanel = new de.phleisch.app.itsucks.gui.job.panel.DownloadJobRegExpRuleChainPanel();
		downloadJobContentFilterPanel = new de.phleisch.app.itsucks.gui.job.panel.DownloadJobContentFilterPanel();

		tabbedPane.addTab("Basic Parameters", downloadJobBasicPanel);

		tabbedPane.addTab("Simple Rules", downloadJobSimpleRulesPanel);

		tabbedPane.addTab("Special Rules", downloadJobSpecialRulesPanel);

		tabbedPane.addTab("Advanced RegExp Rules", downloadJobRegExpRulesPanel);

		tabbedPane.addTab("Content Filter", downloadJobContentFilterPanel);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(tabbedPane,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 619,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(tabbedPane,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 598,
				Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private de.phleisch.app.itsucks.gui.job.panel.DownloadJobBasicPanel downloadJobBasicPanel;
	private de.phleisch.app.itsucks.gui.job.panel.DownloadJobContentFilterPanel downloadJobContentFilterPanel;
	private de.phleisch.app.itsucks.gui.job.panel.DownloadJobRegExpRuleChainPanel downloadJobRegExpRulesPanel;
	private de.phleisch.app.itsucks.gui.job.panel.DownloadJobSimpleRulesPanel downloadJobSimpleRulesPanel;
	private de.phleisch.app.itsucks.gui.job.panel.DownloadJobFileSizeRulesPanel downloadJobSpecialRulesPanel;
	private javax.swing.JTabbedPane tabbedPane;
	// End of variables declaration//GEN-END:variables

}