/*
 * TestRegularExpression2Dialog.java
 *
 * Created on __DATE__, __TIME__
 */

package de.phleisch.app.itsucks.gui;

import java.awt.Dialog;

/**
 *
 * @author  __USER__
 */
public class EditRegularExpressionDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -7396066111793340186L;
	private boolean mOk = false;

	/** Creates new form TestRegularExpression2Dialog */
	public EditRegularExpressionDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** Creates new form TestRegularExpression2Dialog */
	public EditRegularExpressionDialog(Dialog parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public void setRegularExpression(String pExpression) {
		this.editRegularExpression2Panel1.setRegularExpression(pExpression);
	}

	public String getRegularExpression() {
		return this.editRegularExpression2Panel1.getRegularExpression();
	}

	public boolean isOk() {
		return mOk;
	}

	//	public boolean isCanceled() {
	//		return mCanceled;
	//	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		editRegularExpression2Panel1 = new de.phleisch.app.itsucks.gui.panel.EditRegularExpressionPanel();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Regular Expression Editor");
		setLocationByPlatform(true);

		jButton1.setText("Ok");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPanel1.add(jButton1);

		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jPanel1.add(jButton2);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(12, 12, 12).add(jPanel1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 858,
						Short.MAX_VALUE).add(12, 12, 12)).add(
				editRegularExpression2Panel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 882,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().add(
						editRegularExpression2Panel1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387,
						Short.MAX_VALUE).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(jPanel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	//GEN-FIRST:event_jButton2ActionPerformed
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}//GEN-LAST:event_jButton2ActionPerformed

	//GEN-FIRST:event_jButton1ActionPerformed
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		mOk = true;
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private de.phleisch.app.itsucks.gui.panel.EditRegularExpressionPanel editRegularExpression2Panel1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}